# Generated by Django 4.0.3 on 2022-03-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidekick', '0004_add_status_created_finished_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredtask',
            name='task_name',
            field=models.CharField(help_text='The task to be run ie. stock --get_stock_updates', max_length=125, unique=True),
        ),
    ]
